theme = "lynx"
title = "Profile"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Tina He"
  headline = "自由隨意，向心所得"
  image = "img/author.JPG"  # path relative to static directory
  email = "jane36742715@gmail.com"
  education = "輔仁大學醫學資訊與創新應用學士學位學程"

  links = [
    { email = "mailto:jane36742715@gmail.com" },
    { link = "https://ithelp.ithome.com.tw/users/20151894" },
    { link = { href = "https://hackmd.io/@CtSze-t7T1GVANgIYXx2og", text = "Hackmd" } },
    { github = "https://github.com/jane901201" },
    { medium = "https://medium.com/" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
